#dependencies
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Zhupiter
tagline:             '追梦不怠'
url:                 http://shadowlance.github.iio
baseurl:             ''
paginate:            10
paginate_path:       "page:num"

# readmore
excerpt_separator:  '<!-- more -->'
